name: CD

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 6 * * 0'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3